-- Mssv: 23110163
-- Ho ten: Nguyen Van Phuc Huy
-- RDBMS: SQL Server
create database csdl_khachsan;
Go
use csdl_khachsan;

create table KHACHLUUTRU(
	SoCC char(12) NOT NULL,
	Ho varchar(30) NOT NULL,
	Ten varchar(15) NOT NULL,
	NgaySinh date,
	SoDT char(10) NOT NULL,
	CONSTRAINT PK_KHACHLUUTRU PRIMARY KEY (SoCC),
);
create table LOAIPHONG(
	LoaiPG char(1) NOT NULL CHECK (LoaiPG IN ('1','2','3')),
	DonGia decimal(10,2) NOT NULL,
	SoGiuong int NOT NULL CHECK (SoGiuong BETWEEN 1 AND 3),
	KieuGiuong int NOT NULL CHECK (KieuGiuong IN (1, 2)),
	CONSTRAINT PK_LOAIPHONG PRIMARY KEY (LoaiPG),
);
create table PHONG(
	SoPG int NOT NULL,
	LoaiPG char(1) NOT NULL CHECK (LoaiPG IN ('1','2','3')),
	ViTri int NOT NULL CHECK (ViTri IN (1, 2, 3)),
	CONSTRAINT PK_PHONG PRIMARY KEY (SoPG),
	CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY (LoaiPG) REFERENCES LOAIPHONG(LoaiPG),
)
create table DATPHONG(
	SoDP int NOT NULL,
	SoPG int NOT NULL,
	LoaiPG char(1) NOT NULL CHECK (LoaiPG IN ('1','2','3')),
	SoCC char(12) NOT NULL,
	NgayDat date NOT NULL,
	CachDat char(1) NOT NULL CHECK (CachDat IN ('A', 'C', 'S', 'V')),
	NgayDen date NOT NULL,
	NgayDi date NOT NULL,
	CONSTRAINT PK_DATPHONG PRIMARY KEY (SoDP),
	CONSTRAINT FK_DATPHONG_PHONG FOREIGN KEY (SoPG) REFERENCES PHONG(SoPG),
	CONSTRAINT FK_DATPHONG_LOAIPHONG FOREIGN KEY (LoaiPG) REFERENCES LOAIPHONG(LoaiPG),
	CONSTRAINT FK_DATPHONG_KHACHLUUTRU FOREIGN KEY (SoCC) REFERENCES KHACHLUUTRU(SoCC),
);

INSERT INTO LOAIPHONG(LoaiPG,DonGia,SoGiuong,KieuGiuong)
VALUES
(1,	950000,	1,	2),
(2,	800000,	2,	1),
(3,	700000,	2,	1);
GO
--INSERT INTO PHONG
INSERT INTO PHONG(SoPG,LoaiPG,ViTri)
VALUES
(100,	1,	1),
(101,	2,	2),
(102,	3,	3);
GO
--INSERT INTO KHACHLUUTRU
--INSERT INTO KHACHLUUTRU  
INSERT INTO KHACHLUUTRU(SoCC, Ho, Ten, NgaySinh, SoDT)  
VALUES  
('51069001234', 'Le Van', 'Tho', '1969-12-01', '332089600'),  
('51175002342', 'Nguyen Thi', 'Hau', '1975-03-20', '985984434');  
GO  

--INSERT INTO DATPHONG  
INSERT INTO DATPHONG(SoDP, SoPG, LoaiPG, SoCC, NgayDat, CachDat, NgayDen, NgayDi)  
VALUES  
(1, 101, '1', '51069001234', '2024-03-01', 'S', '2024-04-28', '2024-04-30'),  
(2, 102, '3', '51175002342', '2024-04-10', 'V', '2024-04-10', '2024-04-11');  
GO

select * from DATPHONG;
UPDATE DATPHONG
SET 
    NgayDen = DATEADD(DAY, 10, NgayDen),
    NgayDi = DATEADD(DAY, 10, NgayDi)
WHERE SoCC = '51069001234';
select * from DATPHONG;
DELETE FROM DATPHONG
WHERE SoCC IN (
    SELECT SoCC
    FROM KHACHLUUTRU
    WHERE SoDT = '985984434'
);
select * from DATPHONG;