CREATE DATABASE TAXI_23110163;
GO
USE TAXI_23110163;

CREATE TABLE LAIXE (
    MaLX     INT          NOT NULL,
    Ho       VARCHAR (15),
    Dem      VARCHAR (15),
    Ten      VARCHAR (15) NOT NULL,
    NgaySinh DATE        ,
    SoGP     CHAR (12)    NOT NULL,
    HanGP    DATE        ,
    CONSTRAINT PK_LAIXE PRIMARY KEY (MaLX)
);

CREATE TABLE LOAI_PHUONGTIEN (
    LoaiPT  INT NOT NULL,
    TenLoai INT NOT NULL,
    CONSTRAINT PK_LOAI_PHUONGTIEN PRIMARY KEY (LoaiPT)
);

CREATE TABLE PHUONGTIEN (
    LoaiPT     INT       NOT NULL,
    SoPT       INT       NOT NULL,
    BienSo     CHAR (10) NOT NULL,
    NamSanXuat INT       NOT NULL,
    ChuPT      INT      ,
    TinhTrang  INT       CHECK (TinhTrang IN (0, 1)),
    CONSTRAINT PK_PHUONGTIEN PRIMARY KEY (SoPT),
    CONSTRAINT FK_PHUONGTIEN_LOAI_PHUONGTIEN FOREIGN KEY (LoaiPT) REFERENCES LOAI_PHUONGTIEN (LoaiPT),
    CONSTRAINT FK_PHUONGTIEN_LAIXE FOREIGN KEY (ChuPT) REFERENCES LAIXE (MaLX)
);

CREATE TABLE CALAMVIEC (
    MaCLV   INT      NOT NULL,
    MaLX    INT      NOT NULL,
    SoPT    INT      NOT NULL,
    BatDau  DATETIME,
    KetThuc DATETIME,
    CONSTRAINT PK_CALAMVIEC PRIMARY KEY (MaCLV),
    CONSTRAINT FK_CALAMVIEC_LAIXE FOREIGN KEY (MaLX) REFERENCES LAIXE (MaLX),
    CONSTRAINT FK_CALAMVIEC_PHUONGTIEN FOREIGN KEY (SoPT) REFERENCES PHUONGTIEN (SoPT)
);
